security:
  basic:
    enabled: false
  user:
    name: admin
    password: 2a10F3GmBtZVvSIwaY4YM0KHOOAifpbzSBqqsnfbjfNqq6Z7Htjgh.xJe

management:
  port: 8081
  security:
    roles: SUPERUSER
    enabled: true
